### ISSUE TITLE
対戦結果が対称的にならない

### ISSUE THREAD

**Issue by shigural** [Tsunehiko511/project-puppeteer#6]
2017/8/4段階での最新プログジェクトファイルにおいて、「テスト」ボタンを実行すると、以下の結果が出力されます。(No.7 と No.10による対戦調べ)
勝者：RED  詳細(赤,青)：残機(4,0)，キングHP(398, 115)
UnityEngine.Debug:LogFormat(String, Object[])
Setting:TestPlay(String) (at Assets/Menu/Script/Setting.cs:32)
Setting:PushTestButton() (at Assets/Menu/Script/Setting.cs:20)
UnityEngine.EventSystems.EventSystem:Update()
勝者：BLUE  詳細(赤,青)：残機(0,2)，キングHP(-59, 173)
UnityEngine.Debug:LogFormat(String, Object[])
Setting:TestPlay(String) (at Assets/Menu/Script/Setting.cs:33)
Setting:PushTestButton() (at Assets/Menu/Script/Setting.cs:20)
UnityEngine.EventSystems.EventSystem:Update()

しかし、本来ならば赤・青側で結果が対照的になるはず。すなわち2番目の出力結果は
「勝者：BLUE  詳細(赤,青)：残機(0,4)，キングHP(115, 398)」となるのが正しいと考えられます。

なお、他のDBを参照して対戦させても結果は対照的にならなかったため、何かしらのバグが推測されます。

**Comment by Tsunehiko511** [comment]
マリオネットAIは同時に移動することがあります。
そのため，例えば赤青のユニットが同じ場所に移動する場合，赤が優先されたり青が優先されたりします。
このことから，同じAIの対戦でも，赤と青では優先度が違うので結果が違うものになると予想されます。
（ただし，移動に関する左右対称性はあまりちゃんと調べていないので本当にバグがあるかも）

**Comment by shigural** [comment]
ありがとうございます！
他の対戦結果から確認した結果からも、バグではなくゲーム上の理由だったようです。

解決したためcloseします。
